export enum TriathlonType {
    SUPER_SPRINT = "SUPER_SPRINT",
    SPRINT = "SPRINT",
    STANDARD = "STANDARD",
    HALF_IRONMAN = "HALF_IRONMAN",
    PTO_T100 = "PTO_T100",
    IRONMAN = "IRONMAN"
}